version: '3.3'
services:

  lane_gcn_environement:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    container_name: lane_gcn
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: "./"
        target: "/work"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [utility, compute, video]
